apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-pipeline
    app.kubernetes.io/component: backend-pipeline
    app.kubernetes.io/instance: backend-pipeline
    app.kubernetes.io/name: backend-pipeline
    app.kubernetes.io/part-of: spring-boot-version-one
    app.openshift.io/runtime-version: latest
  name: backend-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pipeline
  template:
    metadata:
      labels:
        app: backend-pipeline
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/cic-controlbook-dev/backend-pipeline:latest
          imagePullPolicy: Always
          name: backend-pipeline
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
