apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-pipeline
  name: backend-pipeline
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-pipeline